### ISSUE TITLE
None of the games will start

### ISSUE THREAD

**Issue by Darkfiend009** [KenLPham/ArcadeMod#7] opened 2018-08-16 23:04 UTC
Hi there!

I crafted the PacMan and Tetris arcade blocks. Regardless of which i place, when i right-click it says to insert coins but the button doesn't seem to do anything. I also went into the config and tried disabling the need for coins but the machines still will not play.

The mod is a really cool idea and i'm very interested in trying it! Thanks for your time.

**Comment by Darkfiend009** [comment] 2018-08-16 23:14
Mod version 2.1.4
Minecraft version 1.12.2

**Comment by KenLPham** [comment] 2018-08-27 01:45
I just tested it and it works fine for me. Where are the coins in your inventory? How many do you have? When you disabled the coins does the insert coin screen still show up?

**Comment by Mike5357** [comment] 2018-08-27 04:14
Currently also having this issue. The games only work when in creative mode. In survival mode it just says "Insert coin" and clicking the button does nothing.

**Comment by Mike5357** [comment] 2018-08-27 04:21
Error when clicking the button: https://pastebin.com/CkdzLcRL
Could be an incompatibility with Sponge?

Minecraft 1.12.2
Mod Version 2.1.4
Forge 2705
SpongeForge 3392

**Comment by KenLPham** [comment] 2018-08-27 17:59
Im currently testing in forge 2705, spongeforge 3392, mc 1.12.2 and arcademod 2.1.4. Everything is working fine for me.

Do you have anything else installed?

Edit: Are you playing on singleplayer or multiplayer or lan?

**Comment by Mike5357** [comment] 2018-08-27 19:10
Having the issue on multiplayer; the mod works fine on singleplayer.

I removed ALL mods except Arcade mod and SpongeForge, still doesn't work.

**Comment by Mike5357** [comment] 2018-08-27 19:22
Here's the full latest.log with no other mods installed and on a fresh world: https://pastebin.com/dAiMEvpq

I wonder if it has to do with the server being in offline mode / a bungeecord server?

**Comment by KenLPham** [comment] 2018-08-27 20:07
The issue is with arcademod is trying to run client side only code on the server. Sorry about this. It will be fixed in the next release

**Comment by Wattyooo** [comment] 2018-10-07 03:12
Any News on this? I too am experiencing this issue.

**Closed as completed** 2018-10-15 06:03 UTC
Labels: bug
